# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: zenchatai
# "service" is the name of this project. This will also be added to your AWS resource names.
service: CostGuard
app: costguard

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    COST_ALERT_TOPIC: ${env:COST_ALERT_TOPIC}
    COST_ALERT_TABLE: ${env:COST_ALERT_TABLE}
    DAILY_THRESHOLD_PERCENT: ${env:DAILY_THRESHOLD_PERCENT}
    MONTHLY_BUDGET: ${env:MONTHLY_BUDGET}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID, ""}
    USER_POOL_ID: !Ref CostGuardUserPool
    USER_POOL_CLIENT_ID: !Ref CostGuardUserPoolClient
    USERS_TABLE: !Ref UsersTable
    CLOUD_BUDGET_SETTINGS_TABLE: !Ref CloudBudgetSettingsTable
    JWT_SECRET: ${env:JWT_SECRET, "your-jwt-secret-key"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ce:GetCostAndUsage
            - ce:GetDimensionValues
            - ce:GetUsageReport
          Resource: "*"
        - Effect: Allow
          Action:
            - budgets:ViewBudget
            - budgets:DescribeBudgets
            - budgets:DescribeBudget
          Resource: "*"
        - Effect: Allow
          Action:
            - sts:GetCallerIdentity
          Resource: "*"
        - Effect: Allow
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminGetUser
            - cognito-idp:AdminUpdateUserAttributes
            - cognito-idp:AdminDeleteUser
            - cognito-idp:ListUsers
          Resource: !GetAtt CostGuardUserPool.Arn
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt UsersTable.Arn
            - !Sub "${UsersTable.Arn}/index/*"
            - !GetAtt CloudBudgetSettingsTable.Arn
            - !Sub "${CloudBudgetSettingsTable.Arn}/index/*"
        - Effect: Allow
          Action:
            - sns:Publish
          Resource: "*"

functions:
  # Authentication Functions
  signUp:
    handler: src/functions/Auth/signUp.handler
    description: "User registration with Cognito"
    events:
      - http:
          path: auth/signup
          method: post
          cors: true

  signIn:
    handler: src/functions/Auth/signIn.handler
    description: "User login with Cognito"
    events:
      - http:
          path: auth/signin
          method: post
          cors: true

  refreshToken:
    handler: src/functions/Auth/refreshToken.handler
    description: "Refresh JWT token"
    events:
      - http:
          path: auth/refresh
          method: post
          cors: true

  getUserProfile:
    handler: src/functions/Auth/getUserProfile.handler
    description: "Get user profile information"
    events:
      - http:
          path: auth/profile
          method: get
          cors: true

  updateUserProfile:
    handler: src/functions/Auth/updateUserProfile.handler
    description: "Update user profile information"
    events:
      - http:
          path: auth/profile
          method: put
          cors: true

  # Budget Management Functions
  setBudget:
    handler: src/functions/Budget/setBudgetHandler.handler
    description: "Set or update user's cloud budget settings"
    events:
      - http:
          path: budget/set
          method: post
          cors: true

  getBudget:
    handler: src/functions/Budget/getBudgetHandler.handler
    description: "Get user's current budget settings"
    events:
      - http:
          path: budget
          method: get
          cors: true

  # Cost Alert Functions
  costAlert:
    handler: src/functions/CostAlert/costAlertHandler.handler
    description: "Scheduled Lambda to check AWS cost and alert users"
    events:
      - schedule: rate(1 day)

  triggerCostAlert:
    handler: src/functions/CostAlert/costAlertHandler.handler
    description: "Manual trigger for cost alerts (for testing)"
    events:
      - http:
          path: alerts/trigger
          method: post
          cors: true

  getCostData:
    handler: src/functions/CostData/index.GetCostAndUsageHandler
    description: "API to fetch cost data from DynamoDB (protected)"
    events:
      - http:
          path: cost-usage
          method: get
          cors: true

resources:
  Resources:
    # Cognito User Pool
    CostGuardUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool-${sls:stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
        Schema:
          - Name: email
            AttributeDataType: String
            Required: true
            Mutable: true
          - Name: given_name
            AttributeDataType: String
            Required: true
            Mutable: true
          - Name: family_name
            AttributeDataType: String
            Required: true
            Mutable: true
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT

    # Cognito User Pool Client
    CostGuardUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-user-pool-client-${sls:stage}
        UserPoolId: !Ref CostGuardUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        AccessTokenValidity: 24
        IdTokenValidity: 24
        RefreshTokenValidity: 30
        TokenValidityUnits:
          AccessToken: hours
          IdToken: hours
          RefreshToken: days

    # DynamoDB CloudBudgetSettings Table
    CloudBudgetSettingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-cloud-budget-settings-${sls:stage}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: budgetId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: budgetId
            KeyType: RANGE
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    # DynamoDB Users Table
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-users-${sls:stage}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

  Outputs:
    UserPoolId:
      Value: !Ref CostGuardUserPool
      Export:
        Name: ${self:service}-user-pool-id-${sls:stage}

    UserPoolClientId:
      Value: !Ref CostGuardUserPoolClient
      Export:
        Name: ${self:service}-user-pool-client-id-${sls:stage}

    CloudBudgetSettingsTableName:
      Value: !Ref CloudBudgetSettingsTable
      Export:
        Name: ${self:service}-cloud-budget-settings-table-${sls:stage}

plugins:
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies

package:
  individually: true
  patterns:
    - "!.git/**"
    - "!.vscode/**"
    - "!tests/**"
    - "!docs/**"
    - "!*.md"
    - "!.env"
    - "!.gitignore"
    - "!test-auth.js"
    - "!node_modules/**"
    - "!.serverless/**"
    - "!coverage/**"
    - "!jest.config.js"
    - "!eslint.config.js"
    # - "node_modules/@aws-sdk/client-budgets/**"
    # - "node_modules/@aws-sdk/client-cost-explorer/**"
    # - "node_modules/@aws-sdk/client-sts/**"
    # - "node_modules/@aws-sdk/client-cognito-identity-provider/**"
    # - "node_modules/@aws-sdk/client-dynamodb/**"
    # - "node_modules/@aws-sdk/lib-dynamodb/**"
    # - "node_modules/@aws-sdk/client-sns/**"
    # - "node_modules/@smithy/**"
